### ISSUE TITLE
Possible typo in View Model documentation

### ISSUE THREAD

**Issue by eivihnd** [FilledStacks/stacked-docs#58]
### Code of Conduct

- [X] I have read and agree to the Stacked Docs project's [Code of Conduct](https://github.com/FilledStacks/stacked-docs/blob/master/CODE_OF_CONDUCT.md)

### What document on stacked.filledstacks.com is affected?

[Basics in depth -> StreamViewModel](https://stacked.filledstacks.com/docs/basics-in-depth/viewmodels#streamviewmodel)

### What part(s) of the document would you like to see updated?

In the first paragraph of the StreamViewModel in depth info, it states that the ViewModel is automatically rebuilt. As far as I can see it is the View that is automatically rebuilt.

From the docs:
`It will automatically rebuild the ViewModel as new stream values come in.`

Should be:
`It will automatically rebuild the View as new stream values come in.`

**Comment by FilledStacks** [comment]
Thanks @eivihnd I'll update that now.
